/* tslint:disable */
/* eslint-disable */
// @ts-ignore (./UserSignedIn)
var validate=function validate(data,dataPath,parentData,parentDataProperty,rootData){if(!data||"object"!=typeof data||Array.isArray(data))return validate.errors=[{keyword:"type",dataPath:(dataPath||"")+"",schemaPath:"#/type",params:{type:"object"},message:"should be object"}],!1;for(var key0 in data)return validate.errors=[{keyword:"additionalProperties",dataPath:(dataPath||"")+"",schemaPath:"#/additionalProperties",params:{additionalProperty:""+key0},message:"should NOT have additional properties"}],!1;return validate.errors=null,!0};validate.schema={$id:"https://iterative.ly/company/bb7f0e36-f099-4e44-868a-6468cc3aedb3/event/2d8d9756-24b2-4c62-a9a2-f6914315f80d/version/3.0.0",$schema:"http://json-schema.org/draft-07/schema#",title:"User Signed In",description:"Called when a user signs in",type:"object",properties:{},additionalProperties:!1,required:[]},validate.errors=null;

// @ts-ignore (./GuestClicksRegister)
var validate$1=function validate(data,dataPath,parentData,parentDataProperty,rootData){if(!data||"object"!=typeof data||Array.isArray(data))return validate.errors=[{keyword:"type",dataPath:(dataPath||"")+"",schemaPath:"#/type",params:{type:"object"},message:"should be object"}],!1;for(var key0 in data)return validate.errors=[{keyword:"additionalProperties",dataPath:(dataPath||"")+"",schemaPath:"#/additionalProperties",params:{additionalProperty:""+key0},message:"should NOT have additional properties"}],!1;return validate.errors=null,!0};validate$1.schema={$id:"https://iterative.ly/company/bb7f0e36-f099-4e44-868a-6468cc3aedb3/event/606bc227-0d9e-49d3-9c1a-5e48571116c5/version/1.0.0",$schema:"http://json-schema.org/draft-07/schema#",title:"Guest Clicks Register",description:"Called with the user clicks Register",type:"object",properties:{},additionalProperties:!1,required:[]},validate$1.errors=null;

export { validate$1 as GuestClicksRegisterValidator, validate as UserSignedInValidator };
